CREATE TYPE star_rating as ENUM ('1', '2', '3', '4', '5');

CREATE TABLE my_bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating star_rating NOT NULL
);